spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ng-signal-task
    username: ng-signal-user
    password: ngsignalpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  cache:
    type: simple
