openapi: 3.0.0
info:
  title: NgSignalTask API
  description: API for managing tasks in the NgSignalTask application
  version: 1.0.0

paths:
  /tasks:
    get:
      summary: Get a list of tasks
      operationId: getTasks
      responses:
        "200":
          description: A list of tasks
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TasksListResponse"

    post:
      summary: Create a new task
      operationId: createTask
      requestBody:
        description: Task to be created
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTaskRequest"
      responses:
        "201":
          description: Task created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskResponse"

  /tasks/{taskId}:
    get:
      summary: Get a task by ID
      operationId: getTaskById
      parameters:
        - name: taskId
          in: path
          description: ID of the task to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Task details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskResponse"
        "404":
          description: Task not found

    patch:
      summary: Update an existing task
      operationId: updateTask
      parameters:
        - name: taskId
          in: path
          description: ID of the task to update
          required: true
          schema:
            type: string
      requestBody:
        description: Fields to update in the task
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateTaskRequest"
      responses:
        "200":
          description: Task updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TaskResponse"

    delete:
      summary: Delete a task by ID
      operationId: deleteTask
      parameters:
        - name: taskId
          in: path
          description: ID of the task to delete
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Task deleted

components:
  schemas:
    # Task entity model (singular form)
    Task:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the task
        name:
          type: string
          description: Name of the task
        description:
          type: string
          description: Detailed description of the task
        status:
          type: string
          description: Current status of the task (e.g., "in progress", "completed")
        createdDate:
          type: string
          format: date-time
          description: The date and time when the task was created
      required:
        - id
        - name
        - status

    # Collection of Tasks (plural form)
    TasksListResponse:
      type: object
      properties:
        tasks:
          type: array
          items:
            $ref: "#/components/schemas/Task"
        totalCount:
          type: integer
          description: Total number of tasks available
      required:
        - tasks
        - totalCount

    # Single Task response (used for POST, GET, and PUT)
    TaskResponse:
      type: object
      properties:
        task:
          $ref: "#/components/schemas/Task"
      required:
        - task

    # Request model for creating a new task
    CreateTaskRequest:
      type: object
      properties:
        name:
          type: string
          description: Name of the task
        description:
          type: string
          description: Detailed description of the task
        status:
          type: string
          description: Status of the task (e.g., "in progress", "completed")
      required:
        - name
        - status

    # Request model for updating an existing task
    UpdateTaskRequest:
      type: object
      properties:
        name:
          type: string
          description: Name of the task
        description:
          type: string
          description: Detailed description of the task
        status:
          type: string
          description: Status of the task
      required:
        - name
        - status
