version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ng-signal-task-db
    restart: always
    environment:
      POSTGRES_DB: ng-signal-task
      POSTGRES_USER: ng-signal-user
      POSTGRES_PASSWORD: ngsignalpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: ngsignaltask_postgres_data
